### ISSUE TITLE
BoneIO need restart after HomeAssistant restart

### ISSUE THREAD

**Issue by quantum1xyz** [boneIO-eu/boneIO#86]
After restart HA BoneIO switches are unavailable. Boneio service needs to be restarted.

**Comment by pszafer** [comment]
Should be fixed as now retain message is send by default.

**Comment by dziobson** [comment]
The problem still occurs, you still need to reset your BoneIO

**Comment by pszafer** [comment]
Fixed https://github.com/boneIO-eu/app_bbb/releases/tag/v0.3.0
In 0.3.1 I will add power retain option so state of switch would be known as well after restart.
